### ISSUE TITLE
Knowledge duplication

### ISSUE THREAD

**Issue by JustBeYou** [marius004/Messenger-Spammer#1]
As we know, code with no comments at all can be a burden to work with, but overly commented code could be even a bigger mess. 

Take the following example
```
time.sleep(60) # sleep one minute
```
Every time you would like to change the delay time, you would also have to update the comment because the knowledge is duplicated. This is similar to code duplication but in a more subtle way. Now imagine that you have those comments all over the place and you would have to update them all. Probably you will mismatch the code and comments in a few places and the comments will become more misleading than helpful. 

Let the code speak for itself and add comments only when it's relevant to have additional context.

**Comment by marius004** [comment]
Thanks for the advice. I will change the code so that it doesn't contain overly commented code. I thought it might have been easier and useful for the folks that want to use my code.
